In [2]:
import os
import sys
import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
import matplotlib.pyplot as plt

import smoothie
smoothie.suppress_warnings()

In [3]:
def pcc_cutoff_for_top_x_percent(pearsonR_mat, top_x_percent):
    upper_tri = pearsonR_mat[np.triu_indices_from(pearsonR_mat, k=1)]
    cutoff = np.percentile(upper_tri, 100 - top_x_percent)
    return cutoff

In [4]:
pearsonR_mat_mouse = np.load("../data/mouse_E16.5_E1S1_pearsonR.npy")
gene_names_mouse = np.load("../data/mouse_E16.5_E1S1_gene_names.npy", allow_pickle=True)

pearsonR_mat_human = np.load("../data/GSM9629357_CS23_E2S1_bin1_pearsonR.npy")
gene_names_human = np.load("../data/GSM9629357_CS23_E2S1_bin1_gene_names.npy", allow_pickle=True)

In [ ]:
edge_list_mouse, node_label_df_mouse = smoothie.make_spatial_network(
    pearsonR_mat=pearsonR_mat_mouse, # don't change
    gene_names=gene_names_mouse, # don't change
    pcc_cutoff=float(pcc_cutoff_for_top_x_percent(pearsonR_mat_mouse, 0.2)),
    clustering_power=3,
    output_folder='../Cytoscape'
)

# Filter node_label_df for only genes within modules of size 2 or more.
modules_df_mouse = node_label_df_mouse.groupby('module_label').filter(lambda x: len(x) >= 2)

# Examine modules
modules_df_mouse

,name,module_label,degree,weighted_degree,rescaled_weighted_degree,clustering_coeff,margin_score
0,Tuba1a,1,1443,798.810022,72.584718,0.246610,0.818520
1,Rtn1,1,1336,741.444432,65.579906,0.270766,0.929648
2,Crmp1,1,1285,706.122907,58.774399,0.294389,0.945978
3,Tubb2b,1,1392,755.122716,58.296505,0.263269,0.898497
4,Basp1,1,1397,761.547081,57.685575,0.258813,0.901713
...,...,...,...,...,...,...,...
5811,Gm26752,265,1,0.634809,0.057955,0.000000,1.000000
5812,1110065P20Rik,266,1,0.654376,0.073999,0.000000,1.000000
5813,Mtf1,266,1,0.654376,0.073999,0.000000,1.000000
5814,Emc4,267,64,27.435486,0.118542,0.970734,0.998465
5815,AC124490.1,267,5,2.348805,0.108484,1.000000,0.999913

In [5]:
edge_list_human, node_label_df_human = smoothie.make_spatial_network(
    pearsonR_mat=pearsonR_mat_human, # don't change
    gene_names=gene_names_human, # don't change
    pcc_cutoff=float(pcc_cutoff_for_top_x_percent(pearsonR_mat_human, 0.2)),
    clustering_power=3,
    output_folder='../Cytoscape'
)

# Filter node_label_df for only genes within modules of size 2 or more.
modules_df_human = node_label_df_human.groupby('module_label').filter(lambda x: len(x) >= 2)

# Examine modules
modules_df_human

,name,module_label,degree,weighted_degree,rescaled_weighted_degree,clustering_coeff,margin_score
0,RPL13A,1,3507,698.421964,6.358345e+01,0.109790,0.895193
1,EEF1A1,1,3625,719.089613,6.314508e+01,0.103626,0.897287
2,RPS2,1,3516,694.103820,5.867707e+01,0.109378,0.889893
3,RPS8,1,3512,687.735340,5.827872e+01,0.109110,0.895637
4,RPS23,1,3499,688.178222,5.818667e+01,0.110380,0.905149
...,...,...,...,...,...,...,...
13162,AC099340.1,1531,1,0.116669,9.199087e-06,0.000000,1.000000
13163,CSF2RB,1532,1,0.105964,7.508389e-07,0.000000,1.000000
13164,FTH1P16,1532,1,0.105964,7.508389e-07,0.000000,1.000000
13165,MESTIT1,1533,1,0.141098,1.107964e-04,0.000000,1.000000
13166,PKD2L1,1533,1,0.141098,1.107964e-04,0.000000,1.000000